import { z } from "zod";
import { SLUG_MAX_LENGTH, SLUG_REGEX } from "../utils/slug";
import { requireAtLeastOneKey } from "./primitives";

/**
 * Article — a knowledge-base document (markdown). Simple wiki: no versioning/tags/FTS
 * (docs/03-decisions/0021-knowledge-base-design.md). Single source of truth for api and web.
 * Authorship/visibility rules (DRAFT private to author, author-only writes) live in the service,
 * driven by the X-User-Id shim (docs/03-decisions/0022-draft-visibility-auth-shim.md).
 *
 * Date fields are ISO-8601 strings (the wire shape) — see the note in article-category.ts.
 */

/** Publication state. DRAFT is author-private; PUBLISHED is team-visible. */
export const ArticleStatusSchema = z.enum(["DRAFT", "PUBLISHED"]);

// TODO(metadata): once articles need typed extras (estimatedReadingTime, externalLinks, …), validate
// this against a real schema. For now any JSON object is accepted — same debt as Asset.specs.
// See docs/03-decisions/0007-flexible-asset-specs-jsonb.md.
const ArticleMetadataSchema = z.record(z.string(), z.unknown());

/** A user-supplied slug: lowercase [a-z0-9] groups joined by single hyphens, ≤60 chars. */
const SlugSchema = z
  .string()
  .trim()
  .min(1)
  .max(SLUG_MAX_LENGTH)
  .regex(
    SLUG_REGEX,
    "slug must be lowercase letters, numbers and single hyphens (e.g. 'network-setup')",
  );

/** The full persisted Article entity (API representation of the `articles` row). */
export const ArticleSchema = z.object({
  id: z.cuid(),
  slug: z.string(),
  title: z.string().min(1),
  content: z.string(),
  excerpt: z.string().nullable(),
  status: ArticleStatusSchema,
  categoryId: z.cuid(),
  authorId: z.uuid(),
  lastEditedById: z.uuid().nullable(),
  publishedAt: z.iso.datetime().nullable(),
  metadata: ArticleMetadataSchema.nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  deletedAt: z.iso.datetime().nullable(),
});

/**
 * Payload to create an Article. `authorId` is NOT here — it comes from the caller (X-User-Id),
 * never the body ([[0022]]). `slug` is optional (autogenerated from `title` when omitted); `status`
 * defaults to DRAFT.
 */
export const CreateArticleSchema = z.strictObject({
  title: z.string().trim().min(1).max(200),
  slug: SlugSchema.optional(),
  content: z.string().min(1),
  excerpt: z.string().trim().min(1).max(280).optional(),
  status: ArticleStatusSchema.default("DRAFT"),
  categoryId: z.cuid(),
  metadata: ArticleMetadataSchema.optional(),
});

/**
 * Partial update (an empty body is rejected). Excludes `status` (use publish/unpublish) and
 * `authorId` (immutable). The editor is recorded from the caller (X-User-Id → `lastEditedById`),
 * not the body.
 */
export const UpdateArticleSchema = requireAtLeastOneKey(
  z
    .strictObject({
      title: z.string().trim().min(1).max(200),
      slug: SlugSchema,
      content: z.string().min(1),
      excerpt: z.string().trim().min(1).max(280),
      categoryId: z.cuid(),
      metadata: ArticleMetadataSchema,
    })
    .partial(),
);

/**
 * Non-file fields of the multipart import (`POST /articles/import`). The file itself is handled
 * separately. `title`/`slug` are inferred from the filename/title when omitted. See [[0021]].
 */
export const ImportArticleSchema = z.strictObject({
  categoryId: z.cuid(),
  status: ArticleStatusSchema.default("DRAFT"),
  title: z.string().trim().min(1).max(200).optional(),
  slug: SlugSchema.optional(),
});

export type ArticleStatus = z.infer<typeof ArticleStatusSchema>;
export type Article = z.infer<typeof ArticleSchema>;
export type CreateArticle = z.infer<typeof CreateArticleSchema>;
export type UpdateArticle = z.infer<typeof UpdateArticleSchema>;
export type ImportArticle = z.infer<typeof ImportArticleSchema>;
