import { z } from "zod";
import { RoleSchema, type Role } from "./user";

/**
 * Permission catalog — Roles & Permissions v2 (ADR-0046). The SHARED vocabulary of every
 * authorization-relevant capability in lazyit, expressed as frozen `domain:action` strings.
 *
 * This is the FOUNDATION (P0+P1): the catalog + the wire shape only. Nothing consumes it yet — the
 * `@RequirePermission` decorator/guard, GET annotation, `@Roles` migration and the config endpoints
 * are later waves (ADR-0046 §Phased delivery). It is purely additive and behavior-preserving.
 *
 * Design notes:
 *   - The catalog is **catalog-as-code**: a closed, reviewable zod enum, not a free-form string or a
 *     DB-driven dictionary. A typo can't mint a permission; CI fails on an unknown literal.
 *   - It is **reusable beyond humans**: the same vocabulary will later authorize service accounts
 *     (ADR-0046 "unified foundation + SA fast-follow"), so it is deliberately NOT coupled to the
 *     `User`/`Role` model — it is a flat capability list.
 *   - Authorization stays **DB-first** (INV-1, ADR-0043 #1): permissions resolve from `RolePermission`
 *     DB rows, NEVER from a token claim. This file is only the contract for the wire/seed shape.
 *   - Permissions are **lazyit-local**: they NEVER sync to the IdP. Only the 3 coarse roles keep their
 *     existing `grantRole` write-back (ADR-0043 §3). Do not couple this catalog to Zitadel.
 */

/**
 * Domains — the existing API modules plus the forward-looking `settings` (instance configuration,
 * today served by the `config` module). Each domain is the noun half of a `domain:action` permission.
 * Order is alphabetical-by-area for readability; it carries no semantics.
 */
export const PERMISSION_DOMAINS = [
  "asset",
  "application",
  "accessGrant",
  "consumable",
  "article", // the Knowledge Base (KB) — articles
  "location",
  "assetModel",
  "category", // the four category taxonomies (asset/application/article/consumable categories)
  "user",
  "dashboard",
  "search",
  "logs", // the estate-wide activity history (Reports/Informes); read is ADMIN-only by default
  "settings",
  "workflow", // the Applications Workflow Engine (epic #248) — pre-provisioned RBAC; NO routes yet
  "notification", // the in-app notification bell (ADR-0056) — operational nudges; read is ADMIN-only
] as const;
export type PermissionDomain = (typeof PERMISSION_DOMAINS)[number];

/**
 * Base CRUD-ish actions every domain shares. The coarse capability verbs (below) are layered ON TOP
 * for the operations today's ADMIN gates cover that aren't a plain write/delete.
 */
export const PERMISSION_BASE_ACTIONS = ["read", "write", "delete"] as const;
export type PermissionBaseAction = (typeof PERMISSION_BASE_ACTIONS)[number];

/**
 * The frozen Permission catalog: every `domain:action` literal lazyit authorizes against. It is the
 * single source of truth for the zod enum below and is intentionally explicit (not generated by a
 * cross-product) so each capability is greppable and reviewable, including the coarse verbs.
 *
 * Coarse capability verbs (beyond read/write/delete) map 1:1 to today's ADMIN-only gates (ADR-0040):
 *   - `accessGrant:grant` — open / revoke / patch a grant, and batch-revoke (the AccessGrant writes).
 *   - `user:manage`       — user administration: create / update (incl. role) / offboard / restore.
 *   - `settings:manage`   — instance configuration (the `settings`/config admin surface).
 *
 * The `workflow` domain (Applications Workflow Engine, epic #248) is pre-provisioned here as
 * catalog-as-code ONLY — there are no engine routes/entities yet. Its verbs are deliberately split by
 * sensitivity (synthesis §5 / security.md §4): a plain `:read` plus four coarse verbs, with
 * `workflow:secrets` kept DISTINCT from `workflow:manage` so credential-holding can be a separate
 * duty from authoring the automation logic (who writes the workflow ≠ who holds the Jira token):
 *   - `workflow:read`    — view workflow definitions, run history and the manual-task inbox
 *     (sensitive — run history reveals who-gets-provisioned-where; treated like `logs:read`, ADMIN-only).
 *   - `workflow:manage`  — configure the engine + connections (create/edit/delete/enable definitions).
 *   - `workflow:run`     — manually trigger / re-run / retry a run.
 *   - `workflow:task`    — complete a manual task step (permission alone is not enough; the completer
 *     must also be a valid assignee — the engine's IDOR guard, enforced server-side when the engine ships).
 *   - `workflow:secrets` — configure / enter / rotate per-app connector credentials (separation of duties).
 *
 * Read-only domains (`dashboard`, `search`) expose only `:read`; they have no mutation surface today.
 */
export const PERMISSIONS = [
  // asset
  "asset:read",
  "asset:write",
  "asset:delete",
  // application
  "application:read",
  "application:write",
  "application:delete",
  // accessGrant — `grant` is the coarse ADMIN capability (open/revoke/patch/batch-revoke)
  "accessGrant:read",
  "accessGrant:write",
  "accessGrant:delete",
  "accessGrant:grant",
  // consumable
  "consumable:read",
  "consumable:write",
  "consumable:delete",
  // article (KB)
  "article:read",
  "article:write",
  "article:delete",
  // location
  "location:read",
  "location:write",
  "location:delete",
  // assetModel
  "assetModel:read",
  "assetModel:write",
  "assetModel:delete",
  // category (the four category taxonomies)
  "category:read",
  "category:write",
  "category:delete",
  // user — `manage` is the coarse ADMIN capability (create/update/offboard/restore)
  "user:read",
  "user:write",
  "user:delete",
  "user:manage",
  // dashboard (read-only surface)
  "dashboard:read",
  // search (read-only surface)
  "search:read",
  // logs (read-only surface) — the activity history; the FIRST admin-only read (see ADMIN_ONLY_READS)
  "logs:read",
  // settings (instance configuration) — `manage` is the coarse ADMIN capability
  "settings:read",
  "settings:manage",
  // workflow (Applications Workflow Engine, epic #248) — pre-provisioned; ALL ADMIN-only by default.
  // `read` is admin-only (see ADMIN_ONLY_READS, treated like logs:read); `manage`/`run`/`task`/`secrets`
  // are coarse verbs. `secrets` is DISTINCT from `manage` for separation of duties (synthesis §5).
  "workflow:read",
  "workflow:manage",
  "workflow:run",
  "workflow:task",
  "workflow:secrets",
  // notification (in-app notification bell, ADR-0056) — a read-only surface. `notification:read` is
  // ADMIN-only by default (see ADMIN_ONLY_READS, treated like logs:read): notifications surface
  // sensitive operational state (who got critical-app access, who was made ADMIN), so admin-only is the
  // safe default. The bell + its four poll endpoints are gated on it. There is no `:write` — admins
  // mark notifications read via the PATCH endpoints, which is not a catalog mutation permission.
  "notification:read",
] as const;

/**
 * A single permission literal (`domain:action`). The zod enum is the runtime validator; the inferred
 * `Permission` type is the compile-time contract shared by `api` (seed/guard) and `web` (config UI,
 * later). Mirrors {@link PERMISSIONS} exactly.
 */
export const PermissionSchema = z.enum(PERMISSIONS);
export type Permission = z.infer<typeof PermissionSchema>;

/**
 * The wire shape for the full per-role permission matrix: every {@link Role} mapped to the set of
 * permissions it currently holds. This is what a future config endpoint reads/writes and what the
 * golden test asserts against the seed. It is the materialized view of the `RolePermission` rows.
 *
 * The ADMIN entry is, by decision (ADR-0046), the COMPLETE catalog and is immutable/full — the config
 * surface (a later wave) must never let it be edited, so the last-admin / first-admin invariants and
 * INV-1 stay intact.
 */
export const RolePermissionMatrixSchema = z.record(
  RoleSchema,
  z.array(PermissionSchema),
) satisfies z.ZodType<Record<Role, Permission[]>>;
export type RolePermissionMatrix = z.infer<typeof RolePermissionMatrixSchema>;

/**
 * Every `:read` permission in the catalog — the read surface of all thirteen domains.
 */
export const READ_PERMISSIONS: readonly Permission[] = PERMISSIONS.filter(
  (p): p is Permission => p.endsWith(":read"),
);

/**
 * Every `:write` permission in the catalog. Read-only domains (`dashboard`, `search`) have none, so
 * this is the set of domains with a mutation surface.
 */
export const WRITE_PERMISSIONS: readonly Permission[] = PERMISSIONS.filter(
  (p): p is Permission => p.endsWith(":write"),
);

/**
 * The two reads PRE-TIGHTENED on day one (ADR-0046, CEO decision). The default read-authz rollout is
 * "default-open then tighten": every `<domain>:read` is granted to all three roles to PRESERVE today's
 * behavior (all GETs are reachable by any authenticated user, including VIEWER) — EXCEPT these two,
 * which are the worst read-exposure and are restricted to ADMIN + MEMBER (VIEWER loses them):
 *   - `accessGrant:read` — who has access to what (and to critical apps) is sensitive.
 *   - `user:read`        — the user directory (emails, roles, externalId linkage) is sensitive.
 * This is the ONLY read-behavior change in the v2 foundation; it is intentional and CEO-approved.
 */
export const VIEWER_DENIED_READS = [
  "accessGrant:read",
  "user:read",
] as const satisfies readonly Permission[];

/**
 * The reads that are ADMIN-ONLY by default — strictly MORE restrictive than {@link VIEWER_DENIED_READS}.
 * Where the pre-tightened reads stay open to ADMIN + MEMBER (only VIEWER loses them), an admin-only read
 * is excluded from BOTH MEMBER and VIEWER seed defaults; only ADMIN holds it (via the complete-catalog
 * short-circuit). It is still **configurable** — an ADMIN may grant it to MEMBER/VIEWER from the role
 * matrix (`PUT /config/permissions`) — but it is never seeded to them.
 *
 *   - `logs:read` — the estate-wide activity history (the future Reports/Informes section). Unlike a
 *     per-domain list (which an operator can already see scoped), the cross-cutting activity log
 *     aggregates who-did-what across every domain, so it is the most sensitive read in the catalog and
 *     defaults to ADMIN-only. This is the FIRST admin-only read (ADR-0046 extension, issue #175).
 *   - `workflow:read` — the Applications Workflow Engine's definitions, run history and manual-task
 *     inbox (epic #248). Run history reveals who-gets-provisioned-where and the shape of external
 *     payloads, so it is sensitive and defaults to ADMIN-only — the same posture as `logs:read`
 *     (synthesis §5 / security.md §4). The four coarse workflow verbs (`manage`/`run`/`task`/`secrets`)
 *     are ADMIN-only by construction of the seed (they are neither `:read` nor `:write`); only the
 *     `:read` needs listing here to keep it out of the default-open read tier.
 *   - `notification:read` — the in-app notification bell (ADR-0056). The bell surfaces a curated set of
 *     sensitive operational nudges (access to a critical app was granted, a user was made ADMIN, a
 *     consumable crossed below minimum stock, a workflow needs a human / failed). Who-got-what is
 *     sensitive, so it defaults to ADMIN-only — the same posture as `logs:read` / `workflow:read`. It
 *     is still admin-grantable from the role matrix; it is just never seeded to MEMBER/VIEWER.
 *
 * Catalog invariant: `ADMIN_ONLY_READS` and `VIEWER_DENIED_READS` are disjoint — a read is either
 * pre-tightened (ADMIN + MEMBER) or admin-only (ADMIN), never both.
 */
export const ADMIN_ONLY_READS = [
  "logs:read",
  "workflow:read",
  "notification:read",
] as const satisfies readonly Permission[];

/**
 * The single SOURCE OF TRUTH for the seeded per-role permission matrix (ADR-0046, P1). The Prisma seed
 * writes EXACTLY this, and the golden Jest test asserts the seeded rows equal EXACTLY this — derive,
 * never hand-list, so the two can never drift. Built 1:1 from the ADR-0040 capability matrix with the
 * CEO's read pre-tightening:
 *   - ADMIN  = ALL permissions (the complete catalog) — immutable/full (never editable).
 *   - MEMBER = all `:read` + all `:write`, MINUS the admin-only reads ({@link ADMIN_ONLY_READS}). The
 *     MEMBER-tier capability-verb set is EMPTY: every coarse verb — accessGrant:grant, user:manage,
 *     settings:manage — and every `:delete` is ADMIN-only per ADR-0040.
 *   - VIEWER = all `:read` EXCEPT the pre-tightened reads ({@link VIEWER_DENIED_READS}) AND the
 *     admin-only reads ({@link ADMIN_ONLY_READS}).
 *
 *   - {@link ADMIN_ONLY_READS} (`logs:read`, `workflow:read`) are excluded from BOTH MEMBER and VIEWER —
 *     strictly more restrictive than the pre-tightening: only ADMIN holds them by default (still
 *     admin-grantable).
 *   - The `workflow` verbs (epic #248) follow a SAFE DEFAULT of ADMIN-only: `workflow:read` via
 *     {@link ADMIN_ONLY_READS}, and the coarse `workflow:manage`/`run`/`task`/`secrets` automatically,
 *     since they are neither `:read` nor `:write` and so never enter the MEMBER/VIEWER seed sets. They
 *     remain admin-grantable from the role matrix (with the ⚠ delegation UX), like the other coarse verbs.
 *
 * Permissions are sorted by their catalog order for a stable, reviewable shape.
 */
export function buildDefaultRolePermissions(): RolePermissionMatrix {
  const order = (p: Permission) => PERMISSIONS.indexOf(p);
  const sorted = (perms: readonly Permission[]): Permission[] =>
    [...new Set(perms)].sort((a, b) => order(a) - order(b));

  const isAdminOnlyRead = (p: Permission): boolean =>
    ADMIN_ONLY_READS.includes(p as (typeof ADMIN_ONLY_READS)[number]);
  const isViewerDeniedRead = (p: Permission): boolean =>
    VIEWER_DENIED_READS.includes(p as (typeof VIEWER_DENIED_READS)[number]);

  // MEMBER gets every read+write EXCEPT the admin-only reads (the pre-tightened reads stay — they are
  // ADMIN + MEMBER). VIEWER gets every read minus BOTH the pre-tightened and the admin-only reads.
  const memberReads = READ_PERMISSIONS.filter((p) => !isAdminOnlyRead(p));
  const viewerReads = READ_PERMISSIONS.filter(
    (p) => !isViewerDeniedRead(p) && !isAdminOnlyRead(p),
  );

  return {
    ADMIN: sorted(PERMISSIONS),
    MEMBER: sorted([...memberReads, ...WRITE_PERMISSIONS]),
    VIEWER: sorted(viewerReads),
  };
}

/**
 * The materialized default matrix (the value of {@link buildDefaultRolePermissions}). Importable
 * directly by the seed and the golden test as the one shared definition.
 */
export const DEFAULT_ROLE_PERMISSIONS: RolePermissionMatrix =
  buildDefaultRolePermissions();

/* ──────────────────────────────────────────────────────────────────────────────────────────────
 * P5 — the CONFIGURABLE surface (ADR-0046 §Phased delivery P5): the wire contracts for the ADMIN
 * config endpoints (GET/PUT /config/permissions) and the caller's effective permissions
 * (GET /config/my-permissions). The catalog itself (above) is frozen; these only describe the
 * editable surface around it.
 * ────────────────────────────────────────────────────────────────────────────────────────────── */

/**
 * The set of roles whose permissions are EDITABLE through the config surface. ADMIN is deliberately
 * absent: it is immutable/full (ADR-0046 — the entire catalog, never editable), so the PUT body can
 * never even name it. Only `MEMBER` and `VIEWER` are configurable within the catalog.
 */
export const EDITABLE_ROLES = ["MEMBER", "VIEWER"] as const;
export type EditableRole = (typeof EDITABLE_ROLES)[number];

/**
 * A single role's desired permission list in a PUT body: a deduplicated, catalog-validated array of
 * `Permission` literals. An unknown literal fails the `PermissionSchema` enum (→ 400). Order is not
 * significant; duplicates are squashed so the audit diff is computed against a clean set.
 */
const PermissionSetSchema = z
  .array(PermissionSchema)
  .transform((perms) => [...new Set(perms)]);

/**
 * Request body for `PUT /config/permissions` (ADR-0046 P5). Replaces the MEMBER and VIEWER permission
 * sets wholesale (a full PUT, not a patch); both keys are REQUIRED. The ADMIN row is IMMUTABLE and is
 * not a key here — `.strict()` rejects any extra key (including `ADMIN`) with a 400, so an attempt to
 * edit ADMIN can never be silently accepted. Every listed permission is validated against the frozen
 * `@lazyit/shared` catalog; an unknown permission → 400. Granting MEMBER/VIEWER any catalog permission
 * (even a `:delete` or a coarse verb) is intentional — the only guardrails are ADMIN-immutable and
 * catalog-membership (ADR-0046 P5).
 */
export const UpdateRolePermissionsSchema = z
  .object({
    MEMBER: PermissionSetSchema,
    VIEWER: PermissionSetSchema,
  })
  .strict();
export type UpdateRolePermissions = z.infer<typeof UpdateRolePermissionsSchema>;

/**
 * Response for `GET /config/my-permissions` (ADR-0046 P5) — the CALLER's effective permission set, so
 * the frontend can derive `can('domain:action')` without polluting the `User` wire shape. Resolved via
 * the `PermissionResolverService` (DB-first; ADMIN → the complete catalog). `role` is the caller's
 * fixed role; `permissions` is the flat list of catalog literals that role currently holds.
 */
export const MyPermissionsSchema = z.object({
  role: RoleSchema,
  permissions: z.array(PermissionSchema),
});
export type MyPermissions = z.infer<typeof MyPermissionsSchema>;

/**
 * The direction of a single audited permission edit (ADR-0046 P5), mirroring the `PermissionAuditAction`
 * DB enum: `grant` = the permission was added to a role's set on a PUT; `revoke` = it was removed.
 * Lower-case on the wire (the API surface), upper-case in the DB enum.
 */
export const PERMISSION_AUDIT_ACTIONS = ["grant", "revoke"] as const;
export const PermissionAuditActionSchema = z.enum(PERMISSION_AUDIT_ACTIONS);
export type PermissionAuditAction = z.infer<typeof PermissionAuditActionSchema>;
