import { z } from "zod";
import { RoleSchema, type Role } from "./user";

/**
 * Permission catalog — Roles & Permissions v2 (ADR-0046). The SHARED vocabulary of every
 * authorization-relevant capability in lazyit, expressed as frozen `domain:action` strings.
 *
 * This is the FOUNDATION (P0+P1): the catalog + the wire shape only. Nothing consumes it yet — the
 * `@RequirePermission` decorator/guard, GET annotation, `@Roles` migration and the config endpoints
 * are later waves (ADR-0046 §Phased delivery). It is purely additive and behavior-preserving.
 *
 * Design notes:
 *   - The catalog is **catalog-as-code**: a closed, reviewable zod enum, not a free-form string or a
 *     DB-driven dictionary. A typo can't mint a permission; CI fails on an unknown literal.
 *   - It is **reusable beyond humans**: the same vocabulary will later authorize service accounts
 *     (ADR-0046 "unified foundation + SA fast-follow"), so it is deliberately NOT coupled to the
 *     `User`/`Role` model — it is a flat capability list.
 *   - Authorization stays **DB-first** (INV-1, ADR-0043 #1): permissions resolve from `RolePermission`
 *     DB rows, NEVER from a token claim. This file is only the contract for the wire/seed shape.
 *   - Permissions are **lazyit-local**: they NEVER sync to the IdP. Only the 3 coarse roles keep their
 *     existing `grantRole` write-back (ADR-0043 §3). Do not couple this catalog to Zitadel.
 */

/**
 * Domains — the existing API modules plus the forward-looking `settings` (instance configuration,
 * today served by the `config` module). Each domain is the noun half of a `domain:action` permission.
 * Order is alphabetical-by-area for readability; it carries no semantics.
 */
export const PERMISSION_DOMAINS = [
  "asset",
  "application",
  "accessGrant",
  "consumable",
  "article", // the Knowledge Base (KB) — articles
  "location",
  "assetModel",
  "category", // the four category taxonomies (asset/application/article/consumable categories)
  "user",
  "dashboard",
  "search",
  "settings",
] as const;
export type PermissionDomain = (typeof PERMISSION_DOMAINS)[number];

/**
 * Base CRUD-ish actions every domain shares. The coarse capability verbs (below) are layered ON TOP
 * for the operations today's ADMIN gates cover that aren't a plain write/delete.
 */
export const PERMISSION_BASE_ACTIONS = ["read", "write", "delete"] as const;
export type PermissionBaseAction = (typeof PERMISSION_BASE_ACTIONS)[number];

/**
 * The frozen Permission catalog: every `domain:action` literal lazyit authorizes against. It is the
 * single source of truth for the zod enum below and is intentionally explicit (not generated by a
 * cross-product) so each capability is greppable and reviewable, including the coarse verbs.
 *
 * Coarse capability verbs (beyond read/write/delete) map 1:1 to today's ADMIN-only gates (ADR-0040):
 *   - `accessGrant:grant` — open / revoke / patch a grant, and batch-revoke (the AccessGrant writes).
 *   - `user:manage`       — user administration: create / update (incl. role) / offboard / restore.
 *   - `settings:manage`   — instance configuration (the `settings`/config admin surface).
 *
 * Read-only domains (`dashboard`, `search`) expose only `:read`; they have no mutation surface today.
 */
export const PERMISSIONS = [
  // asset
  "asset:read",
  "asset:write",
  "asset:delete",
  // application
  "application:read",
  "application:write",
  "application:delete",
  // accessGrant — `grant` is the coarse ADMIN capability (open/revoke/patch/batch-revoke)
  "accessGrant:read",
  "accessGrant:write",
  "accessGrant:delete",
  "accessGrant:grant",
  // consumable
  "consumable:read",
  "consumable:write",
  "consumable:delete",
  // article (KB)
  "article:read",
  "article:write",
  "article:delete",
  // location
  "location:read",
  "location:write",
  "location:delete",
  // assetModel
  "assetModel:read",
  "assetModel:write",
  "assetModel:delete",
  // category (the four category taxonomies)
  "category:read",
  "category:write",
  "category:delete",
  // user — `manage` is the coarse ADMIN capability (create/update/offboard/restore)
  "user:read",
  "user:write",
  "user:delete",
  "user:manage",
  // dashboard (read-only surface)
  "dashboard:read",
  // search (read-only surface)
  "search:read",
  // settings (instance configuration) — `manage` is the coarse ADMIN capability
  "settings:read",
  "settings:manage",
] as const;

/**
 * A single permission literal (`domain:action`). The zod enum is the runtime validator; the inferred
 * `Permission` type is the compile-time contract shared by `api` (seed/guard) and `web` (config UI,
 * later). Mirrors {@link PERMISSIONS} exactly.
 */
export const PermissionSchema = z.enum(PERMISSIONS);
export type Permission = z.infer<typeof PermissionSchema>;

/**
 * The wire shape for the full per-role permission matrix: every {@link Role} mapped to the set of
 * permissions it currently holds. This is what a future config endpoint reads/writes and what the
 * golden test asserts against the seed. It is the materialized view of the `RolePermission` rows.
 *
 * The ADMIN entry is, by decision (ADR-0046), the COMPLETE catalog and is immutable/full — the config
 * surface (a later wave) must never let it be edited, so the last-admin / first-admin invariants and
 * INV-1 stay intact.
 */
export const RolePermissionMatrixSchema = z.record(
  RoleSchema,
  z.array(PermissionSchema),
) satisfies z.ZodType<Record<Role, Permission[]>>;
export type RolePermissionMatrix = z.infer<typeof RolePermissionMatrixSchema>;

/**
 * Every `:read` permission in the catalog — the read surface of all twelve domains.
 */
export const READ_PERMISSIONS: readonly Permission[] = PERMISSIONS.filter(
  (p): p is Permission => p.endsWith(":read"),
);

/**
 * Every `:write` permission in the catalog. Read-only domains (`dashboard`, `search`) have none, so
 * this is the set of domains with a mutation surface.
 */
export const WRITE_PERMISSIONS: readonly Permission[] = PERMISSIONS.filter(
  (p): p is Permission => p.endsWith(":write"),
);

/**
 * The two reads PRE-TIGHTENED on day one (ADR-0046, CEO decision). The default read-authz rollout is
 * "default-open then tighten": every `<domain>:read` is granted to all three roles to PRESERVE today's
 * behavior (all GETs are reachable by any authenticated user, including VIEWER) — EXCEPT these two,
 * which are the worst read-exposure and are restricted to ADMIN + MEMBER (VIEWER loses them):
 *   - `accessGrant:read` — who has access to what (and to critical apps) is sensitive.
 *   - `user:read`        — the user directory (emails, roles, externalId linkage) is sensitive.
 * This is the ONLY read-behavior change in the v2 foundation; it is intentional and CEO-approved.
 */
export const VIEWER_DENIED_READS = [
  "accessGrant:read",
  "user:read",
] as const satisfies readonly Permission[];

/**
 * The single SOURCE OF TRUTH for the seeded per-role permission matrix (ADR-0046, P1). The Prisma seed
 * writes EXACTLY this, and the golden Jest test asserts the seeded rows equal EXACTLY this — derive,
 * never hand-list, so the two can never drift. Built 1:1 from the ADR-0040 capability matrix with the
 * CEO's read pre-tightening:
 *   - ADMIN  = ALL permissions (the complete catalog) — immutable/full (never editable).
 *   - MEMBER = all `:read` + all `:write` (the MEMBER-tier capability-verb set is EMPTY: every coarse
 *     verb — accessGrant:grant, user:manage, settings:manage — and every `:delete` is ADMIN-only per
 *     ADR-0040).
 *   - VIEWER = all `:read` EXCEPT the two pre-tightened reads ({@link VIEWER_DENIED_READS}).
 *
 * Permissions are sorted by their catalog order for a stable, reviewable shape.
 */
export function buildDefaultRolePermissions(): RolePermissionMatrix {
  const order = (p: Permission) => PERMISSIONS.indexOf(p);
  const sorted = (perms: readonly Permission[]): Permission[] =>
    [...new Set(perms)].sort((a, b) => order(a) - order(b));

  return {
    ADMIN: sorted(PERMISSIONS),
    MEMBER: sorted([...READ_PERMISSIONS, ...WRITE_PERMISSIONS]),
    VIEWER: sorted(
      READ_PERMISSIONS.filter(
        (p) => !VIEWER_DENIED_READS.includes(p as (typeof VIEWER_DENIED_READS)[number]),
      ),
    ),
  };
}

/**
 * The materialized default matrix (the value of {@link buildDefaultRolePermissions}). Importable
 * directly by the seed and the golden test as the one shared definition.
 */
export const DEFAULT_ROLE_PERMISSIONS: RolePermissionMatrix =
  buildDefaultRolePermissions();
