import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  slugify,
  type ArticleStatus,
  type CreateArticle,
  type ImportArticle,
  type UpdateArticle,
} from '@lazyit/shared';
import { Prisma } from '../../generated/prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import {
  maxImportBytes,
  maxImportMb,
  parseImportFile,
  titleFromFilename,
} from './article-import';

/** Listing filters for GET /articles. */
export interface ArticleListFilters {
  categoryId?: string;
  authorId?: string;
  status?: ArticleStatus;
  q?: string;
}

/** The subset of a multer file the import needs. The controller passes Express.Multer.File. */
export interface UploadedImportFile {
  originalname: string;
  buffer: Buffer;
  size: number;
}

const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Knowledge-base articles. Authorship/visibility (DRAFT private to its author; only the author may
 * write) is enforced here from the X-User-Id shim — when real auth lands, `currentUserId` comes from
 * the JWT and these methods are unchanged. See docs/03-decisions/0022-draft-visibility-auth-shim.md.
 */
@Injectable()
export class ArticlesService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * List non-deleted articles, newest-updated first. PUBLISHED is visible to all; DRAFT only to its
   * author (the current user). Optional filters: category, author, status, and a substring `q` over
   * title/excerpt.
   */
  async findAll(filters: ArticleListFilters, currentUserId?: string) {
    const cu = await this.resolveCurrentUser(currentUserId);
    const and: Prisma.ArticleWhereInput[] = [this.visibilityWhere(cu)];
    if (filters.categoryId) and.push({ categoryId: filters.categoryId });
    if (filters.authorId) and.push({ authorId: filters.authorId });
    if (filters.status) and.push({ status: filters.status });
    if (filters.q) {
      and.push({
        OR: [
          { title: { contains: filters.q, mode: 'insensitive' } },
          { excerpt: { contains: filters.q, mode: 'insensitive' } },
        ],
      });
    }
    return this.prisma.article.findMany({
      where: { deletedAt: null, AND: and },
      orderBy: { updatedAt: 'desc' },
    });
  }

  /** A readable article by id (404 if missing, deleted, or a draft the caller doesn't own). */
  async findOne(id: string, currentUserId?: string) {
    const cu = await this.resolveCurrentUser(currentUserId);
    const article = await this.prisma.article.findFirst({
      where: { id, deletedAt: null },
    });
    if (!article || (article.status === 'DRAFT' && article.authorId !== cu)) {
      throw new NotFoundException(`Article ${id} not found`);
    }
    return article;
  }

  /** Same visibility rules as findOne, looked up by slug. */
  async findBySlug(slug: string, currentUserId?: string) {
    const cu = await this.resolveCurrentUser(currentUserId);
    const article = await this.prisma.article.findFirst({
      where: { slug, deletedAt: null },
    });
    if (!article || (article.status === 'DRAFT' && article.authorId !== cu)) {
      throw new NotFoundException(`Article with slug "${slug}" not found`);
    }
    return article;
  }

  /** Create. Author = the caller (X-User-Id), never the body. Slug autogenerated when omitted. */
  async create(data: CreateArticle, currentUserId?: string) {
    const authorId = await this.requireCurrentUser(currentUserId);
    await this.assertCategoryUsable(data.categoryId);
    const slug = data.slug ?? this.deriveSlug(data.title);
    return this.prisma.article.create({
      data: {
        slug,
        title: data.title,
        content: data.content,
        ...(data.excerpt !== undefined ? { excerpt: data.excerpt } : {}),
        status: data.status,
        publishedAt: data.status === 'PUBLISHED' ? new Date() : null,
        categoryId: data.categoryId,
        authorId,
        ...(data.metadata !== undefined
          ? { metadata: data.metadata as Prisma.InputJsonValue }
          : {}),
      },
    });
  }

  /** Partial update (author only). Records the editor; never changes status (use publish). */
  async update(id: string, data: UpdateArticle, currentUserId?: string) {
    const cu = await this.requireCurrentUser(currentUserId);
    await this.loadOwned(id, cu);
    if (data.categoryId) await this.assertCategoryUsable(data.categoryId);
    const { metadata, ...rest } = data;
    return this.prisma.article.update({
      where: { id },
      data: {
        ...rest,
        lastEditedById: cu,
        ...(metadata !== undefined
          ? { metadata: metadata as Prisma.InputJsonValue }
          : {}),
      },
    });
  }

  /** Soft delete (author only). */
  async remove(id: string, currentUserId?: string) {
    const cu = await this.requireCurrentUser(currentUserId);
    await this.loadOwned(id, cu);
    return this.prisma.article.update({
      where: { id },
      data: { deletedAt: new Date(), lastEditedById: cu },
    });
  }

  /** Publish (author only). Sets publishedAt on the first publish; idempotent if already published. */
  async publish(id: string, currentUserId?: string) {
    const cu = await this.requireCurrentUser(currentUserId);
    const article = await this.loadOwned(id, cu);
    if (article.status === 'PUBLISHED') return article;
    return this.prisma.article.update({
      where: { id },
      data: {
        status: 'PUBLISHED',
        publishedAt: article.publishedAt ?? new Date(),
        lastEditedById: cu,
      },
    });
  }

  /** Unpublish back to DRAFT (author only). Keeps publishedAt ("was published once"). */
  async unpublish(id: string, currentUserId?: string) {
    const cu = await this.requireCurrentUser(currentUserId);
    const article = await this.loadOwned(id, cu);
    if (article.status === 'DRAFT') return article;
    return this.prisma.article.update({
      where: { id },
      data: { status: 'DRAFT', lastEditedById: cu },
    });
  }

  /** Import an article from an uploaded .md/.txt/.docx file. Author = caller. */
  async importArticle(
    file: UploadedImportFile | undefined,
    fields: ImportArticle,
    currentUserId?: string,
  ) {
    const authorId = await this.requireCurrentUser(currentUserId);
    if (!file) {
      throw new BadRequestException('A file is required');
    }
    if (file.size > maxImportBytes()) {
      throw new BadRequestException(
        `File exceeds the ${maxImportMb()} MB import limit`,
      );
    }
    await this.assertCategoryUsable(fields.categoryId);
    const content = await parseImportFile({
      originalname: file.originalname,
      buffer: file.buffer,
    });
    if (!content.trim()) {
      throw new BadRequestException('The imported file has no text content');
    }
    const title = fields.title ?? titleFromFilename(file.originalname);
    const slug = fields.slug ?? this.deriveSlug(title);
    return this.prisma.article.create({
      data: {
        slug,
        title,
        content,
        status: fields.status,
        publishedAt: fields.status === 'PUBLISHED' ? new Date() : null,
        categoryId: fields.categoryId,
        authorId,
      },
    });
  }

  // --- internals -----------------------------------------------------------

  /** PUBLISHED for everyone; plus the caller's own DRAFTs when there is a current user. */
  private visibilityWhere(currentUserId?: string): Prisma.ArticleWhereInput {
    return currentUserId
      ? {
          OR: [
            { status: 'PUBLISHED' },
            { status: 'DRAFT', authorId: currentUserId },
          ],
        }
      : { status: 'PUBLISHED' };
  }

  /**
   * Load an article for a write and enforce author-only: 404 if missing or a draft the caller can't
   * see (hides existence), 403 if it's a published article owned by someone else.
   */
  private async loadOwned(id: string, currentUserId: string) {
    const article = await this.prisma.article.findFirst({
      where: { id, deletedAt: null },
    });
    if (!article) {
      throw new NotFoundException(`Article ${id} not found`);
    }
    if (article.status === 'DRAFT' && article.authorId !== currentUserId) {
      throw new NotFoundException(`Article ${id} not found`);
    }
    if (article.authorId !== currentUserId) {
      throw new ForbiddenException('Only the author can modify this article');
    }
    return article;
  }

  /** Resolve the X-User-Id shim: undefined → anonymous; present must be a valid live user (400). */
  private async resolveCurrentUser(
    currentUserId?: string,
  ): Promise<string | undefined> {
    if (currentUserId === undefined || currentUserId === '') return undefined;
    if (!UUID_REGEX.test(currentUserId)) {
      throw new BadRequestException('X-User-Id is not a valid user id');
    }
    const user = await this.prisma.user.findFirst({
      where: { id: currentUserId, deletedAt: null },
      select: { id: true },
    });
    if (!user) {
      throw new BadRequestException(
        'X-User-Id does not reference a valid user',
      );
    }
    return user.id;
  }

  /** Like resolveCurrentUser but mandatory (writes): 400 if the header is absent. */
  private async requireCurrentUser(currentUserId?: string): Promise<string> {
    const resolved = await this.resolveCurrentUser(currentUserId);
    if (!resolved) {
      throw new BadRequestException(
        'X-User-Id header is required for this operation',
      );
    }
    return resolved;
  }

  private deriveSlug(title: string): string {
    const slug = slugify(title);
    if (!slug) {
      throw new BadRequestException(
        'Could not derive a slug from the title; provide an explicit slug',
      );
    }
    return slug;
  }

  /** 400 if categoryId doesn't reference a live (non-soft-deleted) category. */
  private async assertCategoryUsable(categoryId: string): Promise<void> {
    const category = await this.prisma.articleCategory.findFirst({
      where: { id: categoryId, deletedAt: null },
      select: { id: true },
    });
    if (!category) {
      throw new BadRequestException(
        `categoryId ${categoryId} does not reference a live category`,
      );
    }
  }
}
