/**
 * Slug helpers for knowledge-base Articles. A slug is short and memorable: lowercase [a-z0-9]
 * groups joined by single hyphens, at most SLUG_MAX_LENGTH chars (e.g. "network-setup").
 * Autogenerated from the title but editable (see docs/03-decisions/0021-knowledge-base-design.md).
 * Pure and framework-agnostic, so api and web share one definition.
 */

/** Maximum slug length, in characters. */
export const SLUG_MAX_LENGTH = 60;

/**
 * Valid slug shape: one or more lowercase-alphanumeric groups joined by single hyphens, with no
 * leading, trailing or doubled hyphens. The empty string is invalid.
 */
export const SLUG_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Derive a slug from arbitrary text: lowercase, strip diacritics (an accented "e" becomes "e"),
 * collapse every run of non-alphanumeric characters into a single hyphen, trim hyphens, and cap
 * at SLUG_MAX_LENGTH (re-trimming a hyphen the cut may leave). Returns "" when the input has no
 * alphanumerics — callers decide what to do then (e.g. require an explicit slug).
 */
export function slugify(input: string): string {
  return input
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, SLUG_MAX_LENGTH)
    .replace(/-+$/g, "");
}

/**
 * Find the first free slug for `base`, auto-suffixing `-2`, `-3`, … on collision until one is
 * available. Resolves the [[0021-knowledge-base-design]] open question (settled by ADR-0059 §3): a
 * slug collision no longer returns a bare 409 — both an interactive create and a bulk import mint a
 * frictionless suffixed slug. PURE: the caller supplies `isTaken` (a closure over the set of live
 * slugs, e.g. a DB lookup's results pre-loaded into a `Set`, or an async existence check the caller
 * resolved first), so this stays framework-agnostic and shared by api and web.
 *
 * - `base` is assumed already valid ({@link SLUG_REGEX}) and ≤ {@link SLUG_MAX_LENGTH} — derive it
 *   with {@link slugify} first. If `base` itself is free it is returned unchanged (no suffix).
 * - On collision the suffix is appended as `-N` (N starting at 2). To stay within
 *   {@link SLUG_MAX_LENGTH} the base is **truncated** to make room for the suffix (re-trimming any
 *   trailing hyphen the cut leaves), so the result is always a valid slug ≤ the cap. A base that is
 *   already at/near the cap therefore yields e.g. `…aaa-2` of the bounded length.
 * - `isTaken` is consulted for the base and every candidate; the first `false` wins. The candidate
 *   is checked against the SAME predicate the caller used for `base`, so a freshly-minted slug in a
 *   batch must be recorded by the caller (added to its `Set`) before the next call to avoid a
 *   within-batch duplicate.
 */
export function nextAvailableSlug(
  base: string,
  isTaken: (candidate: string) => boolean,
): string {
  if (!isTaken(base)) return base;
  for (let n = 2; ; n++) {
    const suffix = `-${n}`;
    // Truncate the base so `base + suffix` never exceeds the cap; re-trim a hyphen the cut may
    // expose so the candidate stays a valid slug (no trailing/doubled hyphen).
    const room = SLUG_MAX_LENGTH - suffix.length;
    const trimmedBase = base.slice(0, room).replace(/-+$/g, "");
    const candidate = `${trimmedBase}${suffix}`;
    if (!isTaken(candidate)) return candidate;
  }
}
