/**
 * Slug helpers for knowledge-base Articles. A slug is short and memorable: lowercase [a-z0-9]
 * groups joined by single hyphens, at most SLUG_MAX_LENGTH chars (e.g. "network-setup").
 * Autogenerated from the title but editable (see docs/03-decisions/0021-knowledge-base-design.md).
 * Pure and framework-agnostic, so api and web share one definition.
 */

/** Maximum slug length, in characters. */
export const SLUG_MAX_LENGTH = 60;

/**
 * Valid slug shape: one or more lowercase-alphanumeric groups joined by single hyphens, with no
 * leading, trailing or doubled hyphens. The empty string is invalid.
 */
export const SLUG_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Derive a slug from arbitrary text: lowercase, strip diacritics (an accented "e" becomes "e"),
 * collapse every run of non-alphanumeric characters into a single hyphen, trim hyphens, and cap
 * at SLUG_MAX_LENGTH (re-trimming a hyphen the cut may leave). Returns "" when the input has no
 * alphanumerics — callers decide what to do then (e.g. require an explicit slug).
 */
export function slugify(input: string): string {
  return input
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, SLUG_MAX_LENGTH)
    .replace(/-+$/g, "");
}
